name: linux-x64

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build-linux-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        run: |
          git clone --single-branch -b chromium/5249 https://github.com/google/angle.git .
      - name: Fetch depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
      - name: Build
        run: |
          export PATH="$(pwd)/depot_tools:$PATH"
          python scripts/bootstrap.py
          gclient sync
          gn gen out/Release --args="is_debug=false target_cpu=\"x64\" angle_build_all=false"
          autoninja -C out/Release
      - name: Pack
        run: |
          mkdir angle-linux-x64
          mkdir angle-linux-x64/dist
          rm -rf out/Release/gen
          rm -rf out/Release/obj
          rm -rf out/Release/args.gn
          rm -rf out/Release/build.ninja
          rm -rf out/Release/build.ninja.d
          rm -rf out/Release/toolchain.ninja
          find out/Release -name "*.TOC" -delete
          mv -f out/Release/* angle-linux-x64/dist/
          cp -rf include angle-linux-x64/
          find angle-linux-x64 -name ".clang-format" -delete
          find angle-linux-x64 -name "*.md" -delete
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: angle-linux-x64
          path: angle-linux-x64
