name: macos-x64

on:
  workflow_dispatch:

jobs:
  build-macos-x64:
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        run: |
          git clone --single-branch -b chromium/5249 https://github.com/google/angle.git .
      - name: Fetch depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
      - name: Build
        run: |
          export PATH="$(pwd)/depot_tools:$PATH"
          export DEPOT_TOOLS_UPDATE=0
          python scripts/bootstrap.py
          gclient sync
          gn gen out/Release angle angle_shader_translator --args="is_debug=false target_cpu=\"x64\" is_component_build=false"
          autoninja -C out/Release
      - name: Pack
        run: |
          mkdir angle-macos-x64
          mkdir angle-macos-x64/dist
          rm -rf out/Release/gen
          rm -rf out/Release/obj
          rm -rf out/Release/args.gn
          rm -rf out/Release/build.ninja
          rm -rf out/Release/build.ninja.d
          rm -rf out/Release/toolchain.ninja
          find out/Release -name "*.TOC" -delete
          mv -f out/Release/* angle-macos-x64/dist/
          cp -rf include angle-macos-x64/
          find angle-macos-x64 -name ".clang-format" -delete
          find angle-macos-x64 -name "*.md" -delete
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main
      - name: Move
        working-directory: main
        run: |
          git rm -rf angle-macos-x64 || true
          mv ../angle-macos-x64 .
      - name: Push
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Submit artifact'
          pull: '--rebase'
          cwd: './main/angle-macos-x64/'
